<?php

namespace App\Controller\Admin;

use App\Entity\Area;
use App\Entity\Author;
use App\Entity\Blog;
use App\Entity\Challenge;
use App\Entity\Comment;
use App\Entity\Event;
use App\Entity\Highlight;
use App\Entity\News;
use App\Entity\Project;
use App\Entity\Solution;
use App\Entity\Testimony;
use App\Entity\Topic;
use App\Entity\Type;
use App\Entity\User;
use App\Repository\BlogRepository;
use App\Repository\EventRepository;
use App\Repository\NewsRepository;
use App\Repository\ProjectRepository;
use App\Repository\TestimonyRepository;
use App\Repository\UserRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractDashboardController
{
    public function __construct(
        private readonly ProjectRepository $projectRepository,
        private readonly UserRepository $userRepository,
        private readonly BlogRepository $blogRepository,
        private readonly EventRepository $eventRepository,
        private readonly NewsRepository $newsRepository,
        private readonly TestimonyRepository $testimonyRepository,
    ) {
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/admin', name: 'admin_dashboard')]
    public function index(): Response
    {
        $projects = $this->projectRepository->getTotalNumber();
        $posts = $this->blogRepository->getTotalNumber();
        $news = $this->newsRepository->getTotalNumber();

        return $this->render('admin/index.html.twig', [
            'projects' => $projects,
            'posts' => $posts,
            'news' => $news,
        ]);
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Hatch Innovation Brazil')
            ->setLocales(['en', 'pt_BR']);
    }

    public function configureMenuItems(): iterable
    {
        $numProjects = $this->projectRepository->getTotalNumber();
        $numUsers = $this->userRepository->getTotalNumber();
        $numBlogs = $this->blogRepository->getTotalNumber();
        $numEvents = $this->eventRepository->getTotalNumber();
        $numNews = $this->newsRepository->getTotalNumber();
        $numTestimonial = $this->testimonyRepository->getTotalNumber();

        yield MenuItem::linkToDashboard('Dashboard', 'fa fa-dashboard');
        yield MenuItem::section('Admin');
        yield MenuItem::linkToCrud('Projects', 'fas fa-gear', Project::class)
            ->setBadge($numProjects, 'danger');
        yield MenuItem::linkToCrud('Users', 'fas fa-users', User::class)
            ->setBadge($numUsers, 'danger');
        yield MenuItem::subMenu('Project details');
        yield MenuItem::linkToCrud('Challenges', 'fa-solid fa-trophy', Challenge::class);
        yield MenuItem::linkToCrud('Solutions', 'fa fa-tasks', Solution::class);
        yield MenuItem::linkToCrud('Highlights', 'fa-solid fa-highlighter', Highlight::class);
        yield MenuItem::section('Admin data');
        yield MenuItem::linkToCrud('Area', 'fa fa-arrows', Area::class);
        yield MenuItem::linkToCrud('Topics', 'fas fa-folder', Topic::class);
        yield MenuItem::linkToCrud('Type', 'fa fa-check-square', Type::class);
        yield MenuItem::section('Blog data');
        yield MenuItem::linkToCrud('Posts', 'fa fa-blog', Blog::class)
            ->setBadge($numBlogs, 'info');
        yield MenuItem::linkToCrud('Authors', 'fas fa-user', Author::class);
        yield MenuItem::linkToCrud('Comments', 'fa fa-comment', Comment::class);
        yield MenuItem::section('Homepage data');
        yield MenuItem::linkToCrud('Events', 'fa fa-list', Event::class)
            ->setBadge($numEvents, 'info');
        yield MenuItem::linkToCrud('News', 'fa fa-newspaper-o', News::class)
            ->setBadge($numNews, 'info');
        yield MenuItem::linkToCrud('Testimonials', 'fa fa-quote-left', Testimony::class)
            ->setBadge($numTestimonial, 'info');
        // yield MenuItem::linkToCrud('The Label', 'fas fa-list', EntityClass::class);
        yield MenuItem::section('Links');
        yield MenuItem::linkToUrl('Homepage', 'fas fa-home', $this->generateUrl('app_homepage'));
    }

    public function configureActions(): Actions
    {
        return parent::configureActions()
            ->add(Crud::PAGE_INDEX, Action::DETAIL); // TODO: Change the autogenerated stub
    }
}
